-- Portfolio initial schema. Content is seeded in a later phase; this migration is structure only.

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE profiles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(120) NOT NULL,
    headline        VARCHAR(240),
    short_bio       VARCHAR(500),
    long_bio        TEXT,
    location        VARCHAR(160),
    email           VARCHAR(254),
    github_url      VARCHAR(500),
    linkedin_url    VARCHAR(500),
    website_url     VARCHAR(500),
    resume_url      VARCHAR(500),
    avatar_url      VARCHAR(500),
    availability    VARCHAR(32) NOT NULL DEFAULT 'SELECTIVE',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT profiles_availability_chk CHECK (availability IN ('OPEN', 'SELECTIVE', 'UNAVAILABLE'))
);

CREATE TRIGGER trg_profiles_updated_at
    BEFORE UPDATE ON profiles
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TABLE skill_categories (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(80) NOT NULL,
    slug            VARCHAR(80) NOT NULL,
    sort_order      INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT skill_categories_slug_uk UNIQUE (slug)
);

CREATE TRIGGER trg_skill_categories_updated_at
    BEFORE UPDATE ON skill_categories
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TABLE skills (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id     BIGINT NOT NULL REFERENCES skill_categories (id) ON DELETE RESTRICT,
    name            VARCHAR(80) NOT NULL,
    level           VARCHAR(16) NOT NULL DEFAULT 'WORKING',
    years           NUMERIC(4, 1),
    featured        BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order      INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT skills_level_chk CHECK (level IN ('WORKING', 'STRONG', 'EXPERT'))
);

CREATE INDEX idx_skills_category_id ON skills (category_id);
CREATE INDEX idx_skills_sort_order ON skills (sort_order);

CREATE TRIGGER trg_skills_updated_at
    BEFORE UPDATE ON skills
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TABLE experiences (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company         VARCHAR(160) NOT NULL,
    role            VARCHAR(160) NOT NULL,
    employment_type VARCHAR(32) NOT NULL DEFAULT 'FULL_TIME',
    location        VARCHAR(160),
    company_url     VARCHAR(500),
    start_date      DATE NOT NULL,
    end_date        DATE,
    is_current      BOOLEAN NOT NULL DEFAULT FALSE,
    description     TEXT,
    sort_order      INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT experiences_type_chk CHECK (
        employment_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', 'FREELANCE')
    ),
    CONSTRAINT experiences_dates_chk CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT experiences_current_chk CHECK (NOT is_current OR end_date IS NULL)
);

CREATE INDEX idx_experiences_sort_order ON experiences (sort_order);

CREATE TRIGGER trg_experiences_updated_at
    BEFORE UPDATE ON experiences
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TABLE experience_highlights (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    experience_id   BIGINT NOT NULL REFERENCES experiences (id) ON DELETE CASCADE,
    body            TEXT NOT NULL,
    sort_order      INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_experience_highlights_experience_id ON experience_highlights (experience_id);

CREATE TABLE projects (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug                VARCHAR(120) NOT NULL,
    title               VARCHAR(200) NOT NULL,
    subtitle            VARCHAR(240),
    short_description   VARCHAR(500) NOT NULL,
    full_description    TEXT,
    category            VARCHAR(80),
    status              VARCHAR(16) NOT NULL DEFAULT 'WIP',
    featured            BOOLEAN NOT NULL DEFAULT FALSE,
    published           BOOLEAN NOT NULL DEFAULT FALSE,
    github_url          VARCHAR(500),
    live_url            VARCHAR(500),
    image_url           VARCHAR(500),
    seo_title           VARCHAR(200),
    seo_description     VARCHAR(320),
    sort_order          INT NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT projects_slug_uk UNIQUE (slug),
    CONSTRAINT projects_slug_chk CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    CONSTRAINT projects_status_chk CHECK (status IN ('SHIPPED', 'WIP', 'ARCHIVED'))
);

CREATE INDEX idx_projects_featured ON projects (featured);
CREATE INDEX idx_projects_sort_order ON projects (sort_order);
CREATE INDEX idx_projects_published_featured_sort ON projects (published, featured, sort_order);

CREATE TRIGGER trg_projects_updated_at
    BEFORE UPDATE ON projects
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TABLE project_sections (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      BIGINT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    section_type    VARCHAR(40) NOT NULL,
    heading         VARCHAR(200) NOT NULL,
    body_md         TEXT,
    media_url       VARCHAR(500),
    sort_order      INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_project_sections_project_id ON project_sections (project_id);
CREATE INDEX idx_project_sections_sort_order ON project_sections (project_id, sort_order);

CREATE TRIGGER trg_project_sections_updated_at
    BEFORE UPDATE ON project_sections
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TABLE technologies (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(80) NOT NULL,
    slug            VARCHAR(80) NOT NULL,
    tech_group      VARCHAR(32) NOT NULL DEFAULT 'TOOL',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT technologies_slug_uk UNIQUE (slug),
    CONSTRAINT technologies_name_uk UNIQUE (name),
    CONSTRAINT technologies_group_chk CHECK (
        tech_group IN ('LANGUAGE', 'FRAMEWORK', 'DATABASE', 'CLOUD', 'TOOL', 'AI')
    )
);

CREATE TABLE project_technologies (
    project_id      BIGINT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    technology_id   BIGINT NOT NULL REFERENCES technologies (id) ON DELETE RESTRICT,
    sort_order      INT NOT NULL DEFAULT 0,
    PRIMARY KEY (project_id, technology_id)
);

CREATE INDEX idx_project_technologies_project_id ON project_technologies (project_id);
CREATE INDEX idx_project_technologies_technology_id ON project_technologies (technology_id);

CREATE TABLE contact_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(80) NOT NULL,
    email           VARCHAR(254) NOT NULL,
    subject         VARCHAR(120) NOT NULL,
    message         TEXT NOT NULL,
    status          VARCHAR(16) NOT NULL DEFAULT 'NEW',
    ip_hash         CHAR(64),
    user_agent      VARCHAR(400),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT contact_messages_status_chk CHECK (status IN ('NEW', 'READ', 'REPLIED', 'ARCHIVED'))
);

CREATE INDEX idx_contact_messages_created_at ON contact_messages (created_at);
CREATE INDEX idx_contact_messages_status_created ON contact_messages (status, created_at);

CREATE TRIGGER trg_contact_messages_updated_at
    BEFORE UPDATE ON contact_messages
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- Future admin identities. password_hash is sized for BCrypt; never store plaintext.
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(80) NOT NULL,
    password_hash   VARCHAR(100) NOT NULL,
    role            VARCHAR(32) NOT NULL DEFAULT 'ADMIN',
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT users_username_uk UNIQUE (username),
    CONSTRAINT users_role_chk CHECK (role IN ('ADMIN'))
);

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TABLE github_cache (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cache_key       VARCHAR(80) NOT NULL,
    payload         JSONB NOT NULL,
    expires_at      TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT github_cache_key_uk UNIQUE (cache_key)
);

CREATE INDEX idx_github_cache_expires_at ON github_cache (expires_at);

CREATE TRIGGER trg_github_cache_updated_at
    BEFORE UPDATE ON github_cache
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
